<?php

namespace SoftUniBlogBundle\Repository;

/**
 * addDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class addDateRepository extends \Doctrine\ORM\EntityRepository
{
}
