<?php

namespace SoftUniBlogBundle\Repository;

/**
 * contentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contentRepository extends \Doctrine\ORM\EntityRepository
{
}
